// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type File struct {
	ID         int64
	ParentID   sql.NullInt64
	Path       string
	Name       string
	Size       int64
	IsDir      int64
	ModifiedAt int64
	SyncedAt   int64
}
