// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, parent_id, path, name, size, is_dir, modified_at, synced_at
FROM files
WHERE id = ?
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Name,
		&i.Size,
		&i.IsDir,
		&i.ModifiedAt,
		&i.SyncedAt,
	)
	return i, err
}

const topChildren = `-- name: TopChildren :many
WITH RECURSIVE descendants(seed_id, id, size, is_dir) AS (
    SELECT f0.id, f0.id, f0.size, f0.is_dir FROM files f0 WHERE f0.parent_id = ?
    UNION ALL
    SELECT d.seed_id, f.id, f.size, f.is_dir
    FROM files f JOIN descendants d ON f.parent_id = d.id
)
SELECT
    f.id, f.name, f.is_dir,
    COALESCE(SUM(CASE WHEN d.is_dir = 0 THEN d.size ELSE 0 END), 0) AS total_bytes
FROM descendants d
JOIN files f ON f.id = d.seed_id
GROUP BY f.id, f.name, f.is_dir
ORDER BY total_bytes DESC, f.name ASC
`

type TopChildrenRow struct {
	ID         int64
	Name       string
	IsDir      int64
	TotalBytes interface{}
}

func (q *Queries) TopChildren(ctx context.Context, parentID sql.NullInt64) ([]TopChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, topChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopChildrenRow
	for rows.Next() {
		var i TopChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDir,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topRootChildren = `-- name: TopRootChildren :many
WITH RECURSIVE descendants(seed_id, id, size, is_dir) AS (
    SELECT f0.id, f0.id, f0.size, f0.is_dir
    FROM files f0
    WHERE f0.parent_id = (SELECT id FROM files WHERE parent_id IS NULL LIMIT 1)
    UNION ALL
    SELECT d.seed_id, f.id, f.size, f.is_dir
    FROM files f JOIN descendants d ON f.parent_id = d.id
)
SELECT
    f.id, f.name, f.is_dir,
    COALESCE(SUM(CASE WHEN d.is_dir = 0 THEN d.size ELSE 0 END), 0) AS total_bytes
FROM descendants d
JOIN files f ON f.id = d.seed_id
GROUP BY f.id, f.name, f.is_dir
ORDER BY total_bytes DESC, f.name ASC
`

type TopRootChildrenRow struct {
	ID         int64
	Name       string
	IsDir      int64
	TotalBytes interface{}
}

func (q *Queries) TopRootChildren(ctx context.Context) ([]TopRootChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, topRootChildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopRootChildrenRow
	for rows.Next() {
		var i TopRootChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDir,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFile = `-- name: UpsertFile :one

INSERT INTO files (parent_id, path, name, size, is_dir, modified_at, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    parent_id   = excluded.parent_id,
    name        = excluded.name,
    size        = excluded.size,
    is_dir      = excluded.is_dir,
    modified_at = excluded.modified_at,
    synced_at   = excluded.synced_at
RETURNING id
`

type UpsertFileParams struct {
	ParentID   sql.NullInt64
	Path       string
	Name       string
	Size       int64
	IsDir      int64
	ModifiedAt int64
	SyncedAt   int64
}

// DeleteMissing is NOT sqlc-generated: sqlc v1.30.0 does not support dynamic
// IN-clause slice params for SQLite. It is implemented as raw SQL in store.go.
func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertFile,
		arg.ParentID,
		arg.Path,
		arg.Name,
		arg.Size,
		arg.IsDir,
		arg.ModifiedAt,
		arg.SyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
