// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (parent_id, path, name, size, is_dir, modified_at, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    parent_id   = excluded.parent_id,
    name        = excluded.name,
    size        = excluded.size,
    is_dir      = excluded.is_dir,
    modified_at = excluded.modified_at,
    synced_at   = excluded.synced_at
RETURNING id
`

type UpsertFileParams struct {
	ParentID   sql.NullInt64
	Path       string
	Name       string
	Size       int64
	IsDir      int64
	ModifiedAt int64
	SyncedAt   int64
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertFile,
		arg.ParentID,
		arg.Path,
		arg.Name,
		arg.Size,
		arg.IsDir,
		arg.ModifiedAt,
		arg.SyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
